### ISSUE TITLE
New PresentationRequest Form

### ISSUE THREAD

**Issue by brianorwhatever** [aviarytech/wacinsteins-monster#10]
Fields to enter:
1. user selects schema
  - selector of preloaded JSON-LD contexts
2. once schema has been selected, all of the fields from that context will be displayed and the user selects 1 or more
3. user submits form

![image](https://user-images.githubusercontent.com/7122708/128572216-1adf99ff-113b-47cb-a4d9-da1b9f4534d0.png)

**Comment by Vanderscycle** [comment]
desired implementation:
https://w3id.org/vaccination/v1
https://w3id.org/citizenship/v1
https://www.w3.org/2018/credentials/examples/v1
https://w3id.org/traceability/v1

**Comment by Vanderscycle** [comment]
Closed, the current implementation by @brianorwhatever is much better than my initial code.
