### ISSUE TITLE
Connect vercel deployments to correct backend

### ISSUE THREAD

**Issue by brianorwhatever** [aviarytech/wacinsteins-monster#54]
We should first check if there is an env var which will allow us to force our local development API URL to be set.

If no env var is found the svelte app should grab the current domain `window.location.hostname` and prepend `https://api.` to it. This will allow the deployment to talk to the proper backend

**Comment by brianorwhatever** [comment]
```
`https://api.${window.location.hostname}`
```

**Comment by brianorwhatever** [comment]
backticks in command above

**Comment by Vanderscycle** [comment]
```
const baseUrl: string | boolean = import.meta.env.VITE_API_URL;
baseUrl ? baseUrl : `https://api.${window.location.hostname}`
```
Something like this?

**Comment by brianorwhatever** [comment]
```
const baseUrl = import.meta.env.VITE_API_URL ? import.meta.env.VITE_API_URL : `https://api.${window.location.hostname}`
```
