### ISSUE TITLE
Error in create doc

### ISSUE THREAD

**Issue by Vanderscycle** [aviarytech/wacinsteins-monster#97]
The backend api endpoint should emit a response when there's an error in creating the documents and the frontend should catch and transform the error in a meaningful way to the user.

**Comment by brianorwhatever** [comment]
more error handling in general would be a good thing. the main issue you were having here was because of trying to accept your own invitation. we should have a test for that case.

**Comment by Vanderscycle** [comment]
I think this was solved recently. I don't remember which commit. Tested on production and locally and confirmed the process works correctly.
